"""Generate professional Markdown incident reports from an alert + AI analysis.

Pure, deterministic text generation with no external I/O other than an optional
file write. This makes reports easy to test and safe to regenerate.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from ..models import Alert
from ..ai.schemas import AIAnalysis


class ReportError(Exception):
    """Raised when an incident report cannot be built or written."""


_RISK_EMOJI = {
    "info": "⚪",
    "low": "🟢",
    "medium": "🟡",
    "high": "🟠",
    "critical": "🔴",
}


def _truncate(text: str, limit: int = 2000) -> str:
    if len(text) <= limit:
        return text
    return text[:limit] + " …[truncated]"


def build_markdown_report(
    alert: Alert,
    analysis: AIAnalysis,
    generated_at: datetime | None = None,
) -> str:
    """Build a Markdown incident report string from an alert and its analysis."""
    if alert is None or analysis is None:
        raise ReportError("Both alert and analysis are required to build a report")

    ts = (generated_at or datetime.now(timezone.utc)).strftime("%Y-%m-%d %H:%M:%S UTC")
    emoji = _RISK_EMOJI.get(analysis.risk_level.value, "⚪")

    steps = "\n".join(
        f"{i}. {step}" for i, step in enumerate(analysis.investigation_steps, start=1)
    )
    mitre_ids = ", ".join(alert.mitre.ids) if alert.mitre.ids else "—"
    mitre_tactics = ", ".join(alert.mitre.tactics) if alert.mitre.tactics else "—"
    mitre_techniques = ", ".join(alert.mitre.techniques) if alert.mitre.techniques else "—"
    groups = ", ".join(alert.rule.groups) if alert.rule.groups else "—"

    lines = [
        f"# 🛡️ Incident Report — Alert {alert.id}",
        "",
        f"**Generated:** {ts}  ",
        f"**Risk Level:** {emoji} `{analysis.risk_level.value.upper()}`  ",
        f"**Confidence:** {analysis.confidence_score}/100  ",
        f"**False Positive Probability:** {analysis.false_positive_percent}%",
        "",
        "---",
        "",
        "## 📋 Alert Details",
        "",
        f"- **Alert ID:** `{alert.id}`",
        f"- **Timestamp:** {alert.timestamp.isoformat()}",
        f"- **Severity:** `{alert.severity.value}`",
        f"- **Location:** {alert.location or '—'}",
        "",
        "### 🖥️ Agent",
        "",
        f"- **ID:** `{alert.agent.id}`",
        f"- **Name:** {alert.agent.name}",
        f"- **IP:** {alert.agent.ip or '—'}",
        "",
        "### 📜 Rule",
        "",
        f"- **ID:** `{alert.rule.id}`",
        f"- **Level:** {alert.rule.level}",
        f"- **Description:** {alert.rule.description}",
        f"- **Groups:** {groups}",
        "",
        "### 🎯 MITRE ATT&CK",
        "",
        f"- **IDs:** {mitre_ids}",
        f"- **Tactics:** {mitre_tactics}",
        f"- **Techniques:** {mitre_techniques}",
        "",
        "---",
        "",
        "## 🤖 AI Analysis",
        "",
        "### Summary",
        "",
        analysis.summary,
        "",
        "### Risk Assessment",
        "",
        analysis.risk_assessment,
        "",
        "### 🔍 Investigation Steps",
        "",
        steps,
        "",
        "### 🎭 MITRE Commentary",
        "",
        analysis.mitre_commentary or "_No MITRE commentary provided._",
        "",
        "---",
        "",
        "## 📄 Raw Log",
        "",
        "```",
        _truncate(alert.full_log or "—"),
        "```",
        "",
        "---",
        "",
        "_Generated by AI SOC Assistant._",
    ]
    return "\n".join(lines)


def write_markdown_report(
    alert: Alert,
    analysis: AIAnalysis,
    output_dir: Path,
    generated_at: datetime | None = None,
) -> Path:
    """Build a report and write it to output_dir. Returns the file path."""
    content = build_markdown_report(alert, analysis, generated_at=generated_at)
    try:
        output_dir.mkdir(parents=True, exist_ok=True)
        path = output_dir / f"incident_{alert.id}.md"
        path.write_text(content, encoding="utf-8")
        return path
    except OSError as exc:
        raise ReportError(f"Failed to write report: {exc}") from exc
